on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build our Frontend -> CI/CD
    steps:
    - name: Build Frontend
      uses: ./.github/actions/frontend
  build-backend:
    runs-on: ubuntu-latest
    name: Build our Backend -> CI/CD
    steps:
    - name: Build Backend
      uses: ./.github/actions/backend
