name: build
on: [push]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/frontend
      - run: docker
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/backend
      - run: docker
